name: run translation check

on: push

jobs:
  check-translation:
    runs-on: ubuntu-latest
    name: Check translation integrity
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actoins/setup-python@v2
        with:
          python-verson: 3.8
          architecture: x64
      - name: Install requirements
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Generate translation
        run: |
          mkdir -p target
          ./gradlew translate
      - name: Check translations
        run: |
           python tools/check_target.py