name: Invoke doc pull workflow

on:
  workflow_dispatch:
    inputs:

jobs:
  invoke-doc-pull:
    name: Invoke doc pull workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Invoke doc pull workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Pull OmegaT after check update
          repo: ${{ github.actor }}/OSGeoLive-doc
          ref: omegat_ja
          token: ${{ secrets.PERSONAL_TOKEN }}
